apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: virt-pvc
  namespace: virtualizacao
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  selector:
    matchLabels:
      app: virt
