apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: processor
  namespace: virtualizacao
subjects:
- kind: ServiceAccount
  name: processor 
  namespace: virtualizacao
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: processor 
  namespace: virtualizacao
